# -*- coding: utf-8 -*-
"""halo_dunia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lBJeuISi_bvzVHQgcvIvzgiGEemLRteI
"""

print('hallo dunia!')
print('Belajar Orbit')